### ISSUE TITLE
Invariants, or static/fluid wire image elements?

### ISSUE THREAD

**Issue by tfpauly** [britram/draft-trammell-wire-image#4]
While I do like the new text on invariants, based on our discussion, I wasn't sure if we wanted to be so explicit about the concept of invariants here in the wire-image document. Technically, an "invariant" seems like a contract about how the wire-image will evolve over time, rather than a property of a single wire-image itself. What is or isn't an invariant is very much up to the development of the protocol.

The idea that I thought would be useful to define in the wire image is the fact that certain properties of the wire image lend themselves more or less easily to being invariants—that is, whether they are static (bits at fixed positions) or fluid (timing or ordering of packets that can't be totally controlled by the endpoint anyway); or somewhere in the spectrum in between. These concepts could help advise future definitions of invariants by suggesting which elements are better candidates to be invariant.

**Comment by britram** [comment]
it seems like the second paragraph here could be expanded a bit into a new para in the "invariants" section. I do think we should be explicit about what invariants are, since a large part of the value of this document is IMO defining and explaining terminology, though there's a question as to whether we should refer to quic-invariants or to use-it-or-lose-it.

Will see what I can come up with...

**Comment by britram** [comment]
@tfpauly is what's here better? if so, will go ahead and submit -03.

**Comment by tfpauly** [comment]
Yes, this reads well to me!
